In [35]:
import pandas as pd
data=pd.read_excel("arabaverisi.xlsx")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13119 entries, 0 to 13118
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   year          13119 non-null  int64  
 1   price         13119 non-null  int64  
 2   transmission  13119 non-null  object 
 3   mileage       13119 non-null  int64  
 4   tax           13119 non-null  int64  
 5   mpg           13119 non-null  float64
 6   engineSize    13119 non-null  float64
dtypes: float64(2), int64(4), object(1)
memory usage: 717.6+ KB


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data["transmission"]=le.fit_transform(data["transmission"])


In [33]:
data.head()

year  price  transmission  mileage  tax   mpg  engineSize
0  2005   5200             0    63000  325  32.1         1.8
1  2017  34948             0    27000   20  61.4         2.1
2  2016  49948             0     6200  555  28.0         5.5
3  2016  61948             0    16000  325  30.4         4.0
4  2016  73948             0     4000  325  30.1         4.0

In [22]:
X=data.drop("price",axis=1)
y=data[["price"]]

In [5]:
X.head()

year  transmission  mileage  tax   mpg  engineSize
0  2005             0    63000  325  32.1         1.8
1  2017             0    27000   20  61.4         2.1
2  2016             0     6200  555  28.0         5.5
3  2016             0    16000  325  30.4         4.0
4  2016             0     4000  325  30.1         4.0

In [7]:
y.head()

price
0   5200
1  34948
2  49948
3  61948
4  73948

In [8]:
#statsmodel ile model kurmak
import statsmodels.api as sm

In [9]:
lm=sm.OLS(y,X)   

In [10]:
model=lm.fit()

In [12]:
model.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.929
Model:                            OLS   Adj. R-squared (uncentered):              0.929
Method:                 Least Squares   F-statistic:                          2.879e+04
Date:                Wed, 16 Mar 2022   Prob (F-statistic):                        0.00
Time:                        22:45:33   Log-Likelihood:                     -1.3527e+05
No. Observations:               13119   AIC:                                  2.706e+05
Df Residuals:                   13113   BIC:                                  2.706e+05
Df Model:                           6                                                  
Covariance Type:            nonrobust                                                  
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
year             9.8580      0.234     42.132      0.000       9.399      10.317
transmission   255.7420     46.141      5.543      0.000     165.298     346.186
mileage         -0.2997      0.003    -93.936      0.000      -0.306      -0.293
tax            -17.5368      1.165    -15.057      0.000     -19.820     -15.254
mpg           -159.1524      5.049    -31.523      0.000    -169.049    -149.256
engineSize    1.063e+04    122.101     87.064      0.000    1.04e+04    1.09e+04
==============================================================================
Omnibus:                     8913.233   Durbin-Watson:                   1.697
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           395984.223
Skew:                           2.709   Prob(JB):                         0.00
Kurtosis:                      29.364   Cond. No.                     5.87e+04
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 5.87e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [13]:
#sckitlearn ile model kurma
from sklearn.linear_model import LinearRegression
lm=LinearRegression()

In [14]:
model=lm.fit(X,y)

In [15]:
model.intercept_

array([-4228151.97175067])

In [16]:
model.coef_

array([[ 2.10307916e+03,  4.49954250e+01, -1.39009430e-01,
        -1.10527990e+01, -1.53838449e+02,  1.12063093e+04]])

In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
y.head()

price
0   5200
1  34948
2  49948
3  61948
4  73948

In [19]:
model.predict(X)[0:10]

array([[-8594.87174642],
       [23871.9475814 ],
       [61986.67301762],
       [45987.84810364],
       [47702.11280291],
       [60610.06571538],
       [28199.34965847],
       [19016.50435581],
       [56227.17316435],
       [24962.92066515]])

In [20]:
MSE=mean_squared_error(y,model.predict(X))
MSE

43487917.26358197

In [21]:
import numpy as np
RMSE=np.sqrt(MSE)
RMSE

6594.536925636399

In [22]:
##model tuning -model doğrulama

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=1)

In [25]:
X_train.head()

year  transmission  mileage  tax   mpg  engineSize
1351  2018             0     7047  145  53.3         1.3
2910  2016             1    31879  200  41.5         2.0
1753  2018             3    10997  145  67.3         2.1
8079  2019             0     1000  145  64.2         2.0
921   2017             3    29209  125  56.5         2.1

In [26]:
y_train.head()

price
1351  18885
2910  17298
1753  26281
8079  32069
921   20999

In [27]:
X_test.head()

year  transmission  mileage  tax   mpg  engineSize
10170  2012             0    46000   30  64.2         2.1
9551   2020             3       19  150  36.7         2.0
1790   2013             1    69031  125  51.4         1.6
10018  2015             0    34739  125  56.5         2.1
142    2017             3    21352   20  72.4         2.0

In [28]:
y_test.head()

price
10170  11940
9551   38624
1790    8500
10018  13998
142    20998

In [29]:
lm=LinearRegression()
model=lm.fit(X_train,y_train)

In [30]:
#eğitim hatası
np.sqrt(mean_squared_error(y_train,model.predict(X_train)))

6654.5364191176595

In [31]:
#test hatası
np.sqrt(mean_squared_error(y_test,model.predict(X_test)))

6356.200091666532

In [32]:
#k-katlı cross validation

In [33]:
from sklearn.model_selection import cross_val_score

In [34]:
cross_val_score(model,X_train,y_train,cv= 10,scoring="neg_mean_squared_error")

array([-29612159.44522263, -37050535.68770336, -68073171.68985763,
       -44927797.46059004, -48895841.46166912, -39618934.13021901,
       -46175493.97993807, -45197917.43145218, -55692837.42465687,
       -32406418.21832136])

In [35]:

np.sqrt(np.mean(-cross_val_score(model,X_train,y_train,cv= 10,scoring="neg_mean_squared_error")))

6690.673411022468

In [36]:
from numpy import corrcoef

In [37]:
data.corr()

year     price  transmission   mileage       tax       mpg  \
year          1.000000  0.520712      0.229631 -0.738027  0.012480 -0.094626   
price         0.520712  1.000000      0.141017 -0.537214  0.268717 -0.438445   
transmission  0.229631  0.141017      1.000000 -0.223316  0.005091 -0.023386   
mileage      -0.738027 -0.537214     -0.223316  1.000000 -0.160223  0.202850   
tax           0.012480  0.268717      0.005091 -0.160223  1.000000 -0.513742   
mpg          -0.094626 -0.438445     -0.023386  0.202850 -0.513742  1.000000   
engineSize   -0.142147  0.516126     -0.027505  0.063652  0.338341 -0.339862   

              engineSize  
year           -0.142147  
price           0.516126  
transmission   -0.027505  
mileage         0.063652  
tax             0.338341  
mpg            -0.339862  
engineSize      1.000000